TopNews.Web/Controllers/DashboardController.cs
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TopNews.Core.DTOs.Ip;
using TopNews.Core.DTOs.User;
using TopNews.Core.Interfaces;
using TopNews.Core.Services;
using TopNews.Core.Validation.User;
using TopNews.Web.Models.ViewModels;

namespace TopNews.Web.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly UserService _userService;
        private readonly INetworkAddressService _networkAddressService;

        public DashboardController(UserService userService, INetworkAddressService networkAddressService)
        {
            _userService = userService;
            _networkAddressService = networkAddressService;
        }

        public IActionResult Index()
        {
            return View();
        }

        #region Sign In page
        [AllowAnonymous]
        public async Task<IActionResult> SignInAsync()
        {
            string? ipAddress = HttpContext.Connection.RemoteIpAddress?.ToString();
            NetworkAddressDto? networkAddressDto = await _networkAddressService.Get(ipAddress);
            if (networkAddressDto == null)
            {
                return NotFound();
            }
            bool userAuthenticated = HttpContext.User.Identity.IsAuthenticated;
            if (userAuthenticated)
            {
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignIn(UserLoginDto model)
        {
            LoginUserValidation validator = new LoginUserValidation();
            ValidationResult valationReslt = await validator.ValidateAsync(model);
            if (valationReslt.IsValid) 
            {
                ServiceResponse result = await _userService.LoginUserAsync(model);
                if (result.Success) 
                {
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.AuthError = result.Message;
                return View(model);
            }
            ViewBag.AuthError = valationReslt.Errors.FirstOrDefault();
            return View(model); 
        }
        #endregion

        #region Log out page
        [HttpPost]
        public async Task<IActionResult> LogOut()
        {
            ServiceResponse response = await _userService.SignOutAsync();
            return RedirectToAction(nameof(SignIn));
        }
        #endregion

        #region Get all users page
        public async Task<IActionResult> GetAll()
        {
            ServiceResponse<List<UsersDto>, object> result = await _userService.GetAllAsync();
            return View(result.Payload);
        }
        #endregion

        #region Profile page
        public async Task<IActionResult> Profile(string Id)
        {
            ServiceResponse<UpdateUserDto, object> result = await _userService.GetUpdateUserDtoByIdAsync(Id);
            if (result.Success)
            {
                UpdateProfileVM profile = new UpdateProfileVM()
                {
                    UserInfo = result.Payload,
                };
                return View(profile);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeMainInfo(UpdateUserDto model)
        {
            UpdateUserValidation validator = new UpdateUserValidation();
            ValidationResult validationResult = await validator.ValidateAsync(model);
            if (validationResult.IsValid)
            {
                ServiceResponse result = await _userService.ChangeMainInfoUserAsync(model);
                if (result.Success)
                {
                    return View("Profile", new UpdateProfileVM() { UserInfo = model });
                }
                ViewBag.UserUpdateError = result.Errors.FirstOrDefault();
                return View("Profile", new UpdateProfileVM() { UserInfo = model });
            }
            ViewBag.UserUpdateError = validationResult.Errors[0];
            return View("Profile", new UpdateProfileVM() { UserInfo = model });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePasswordInfo(UpdatePasswordDto model)
        {
            UpdatePasswordValidation validator = new UpdatePasswordValidation();
            ValidationResult validationResult = await validator.ValidateAsync(model);
            if (validationResult.IsValid)
            {
                ServiceResponse result = await _userService.ChangePasswordAsync(model);
                if (result.Success)
                {
                    return RedirectToAction(nameof(SignIn));
                }
                ViewBag.UpdatePasswordError = result.Errors;
                return View(new UpdateProfileVM() { UserInfo = _userService.GetUpdateUserDtoByIdAsync(model.Id).Result.Payload });
            }
            ViewBag.UpdatePasswordError = validationResult.Errors[0];
            return View(new UpdateProfileVM() { UserInfo = _userService.GetUpdateUserDtoByIdAsync(model.Id).Result.Payload });
        }

        #endregion

        #region Create user page
        public async Task<IActionResult> CreateUser()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateUser(CreateUserDto model)
        {
            CreateUserValidation validaor = new CreateUserValidation();
            ValidationResult validationResult = await validaor.ValidateAsync(model);
            if (validationResult.IsValid)
            {
                ServiceResponse response = await _userService.CreateUserAsync(model);
                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.CreateUserError = response.Errors.FirstOrDefault();
                return View();
            }
            ViewBag.CreateUserError = validationResult.Errors.FirstOrDefault();
            return View();
        }

        [AllowAnonymous]
        public async Task<IActionResult> ConfirmEmail(string userid, string token)
        {
            ServiceResponse result = await _userService.ConfirmEmailAsync(userid, token);
            return Redirect(nameof(SignIn));
        }
        #endregion

        #region Delete user page
        public async Task<IActionResult> DeleteUser(string id)
        {
            ServiceResponse<DeleteUserDto, object> result = await _userService.GetDeleteUserDtoByIdAsync(id);
            if (result.Success)
            {
                return View(result.Payload);
            }
            return View(nameof(GetAll));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUser(DeleteUserDto model)
        {
            ServiceResponse result = await _userService.DeleteUserAsync(model);
            if (!result.Success)
            {
                ViewBag.GetAllError = result.Errors.FirstOrDefault();
            }
            return RedirectToAction(nameof(GetAll));
        }
        #endregion

        #region Forgot password page
        [AllowAnonymous]
        public async Task<IActionResult> ForgotPassword()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> ForgotPassword(string email)
        {
            ServiceResponse result = await _userService.ForgotPasswordAsync(email);
            if (result.Success)
            {
                ViewBag.AuthError = "Check your email.";
                return View(nameof(SignIn));
            }
            ViewBag.AuthError = "Something went wrong.";
            return View();
        }
        #endregion

        #region Reset password page
        [AllowAnonymous]
        public async Task<IActionResult> ResetPassword(string email, string token)
        {
            ViewBag.Email = email;
            ViewBag.Token = token;
            return View();
        }

        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> ResetPassword(PasswordRecoveryDto model)
        {
            ServiceResponse result = await _userService.ResetPasswordAsync(model);
            ValidationResult resultValidation = await new PasswordRecoveryValidation().ValidateAsync(model);
            ViewBag.Email = model.Email;
            ViewBag.Token = model.Token;
            if (!resultValidation.IsValid)
            {
                ViewBag.AuthError = resultValidation.Errors.FirstOrDefault();
                return View(nameof(ResetPassword));
            }
            if (result.Success)
            {
                ViewBag.AuthError = result.Message;
                return View(nameof(SignIn));
            }
            ViewBag.AuthError = result.Errors.Any() ? result.Errors.FirstOrDefault() : result.Message;
            return View();
        }
        #endregion

        #region Edit other user page
        public async Task<IActionResult> EditUser(string id)
        {

            ServiceResponse<EditUserDto, object> result = await _userService.GetEditUserDtoByIdAsync(id);
            if (result.Success)
            {
                await LoadRoles();
                return View(result.Payload);
            }
            return View(nameof(Index));
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> EditUser(EditUserDto model)
        {
            ValidationResult validationResult = await new EditUserValidation().ValidateAsync(model);
            if (validationResult.IsValid)
            {

TopNews.Web/Controllers/PostController.cs
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TopNews.Core.DTOs.Category;
using TopNews.Core.DTOs.Post;
using TopNews.Core.Entities.Site;
using TopNews.Core.Interfaces;
using TopNews.Core.Services;
using TopNews.Core.Validation.Category;
using TopNews.Core.Validation.Post;
using X.PagedList;

namespace TopNews.Web.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostService _postService;
        private readonly ICategoryService _categoryService;
        public PostController(IPostService postService, ICategoryService categoryService)
        {
            _postService = postService;
            _categoryService = categoryService;
        }
        public IActionResult Index()
        {
            return RedirectToAction(nameof(GetAll));
        }
        #region Get All page
        [AllowAnonymous]
        public async Task<IActionResult> GetAll(int? page)
        {
            List<PostDto> posts = (await _postService.GetAll()).OrderByDescending(p => p.Id).ToList();
            int pageSize = 20;
            int pageNumber = (page ?? 1);
            return View("GetAll", posts.ToPagedList(pageNumber, pageSize));
        }
        #endregion

        #region Create page
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create()
        {
            await LoadCategories();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create(PostDto model)
        {
            CreatePostValidation validator = new CreatePostValidation();
            ValidationResult validationResult = await validator.ValidateAsync(model);
            if (!validationResult.IsValid)
            {
                ViewBag.AuthError = validationResult.Errors.FirstOrDefault();
                return View();
            }
            IFormFileCollection files = HttpContext.Request.Form.Files;
            model.File = files;
            await _postService.Create(model);
            return RedirectToAction(nameof(GetAll));
        }
        #endregion

        #region Update page
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Update(int id)
        {
            var posts = await _postService.Get(id);
            if (posts == null) return NotFound();
            await LoadCategories();
            return View(posts);
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(PostDto model)
        {
            var validationResult = await new CreatePostValidation().ValidateAsync(model);
            if (validationResult.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                model.File = files;
                await _postService.Update(model);
                return RedirectToAction(nameof(GetAll));
            }
            ViewBag.CreatePostError = validationResult.Errors.FirstOrDefault();
            return View(model);
        }
        #endregion

        #region Delete
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int id)
        {
            PostDto? postDto = await _postService.Get(id);
            if (postDto == null)
            {
                ViewBag.AuthError = "Post not found.";
                return View();
            }
            return View(postDto);
        }
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteById(int id)
        {
            await _postService.Delete(id);
            return RedirectToAction(nameof(GetAll));
        }
        #endregion

        private async Task LoadCategories()
        {
            List<CategoryDto> result = await _categoryService.GetAll();
            @ViewBag.CategoryList = new SelectList((System.Collections.IEnumerable)result,
                nameof(CategoryDto.Id), nameof(CategoryDto.Name)
              );
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> PostsByCategory(int id)
        {
            List<PostDto> posts = await _postService.GetByCategory(id);
            int pageSize = 20;
            int pageNumber = 1;
            return View("GetAll", posts.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Search([FromForm] string searchString)
        {
            List<PostDto> posts = await _postService.Search(searchString);
            int pageSize = 20;
            int pageNumber = 1;
            return View("GetAll", posts.ToPagedList(pageNumber, pageSize));
        }
    }
}

TopNews.Web/Views/Post/Create.cshtml
@using TopNews.Core.DTOs.Post;
@model PostDto;

@{
    ViewData["Title"] = "Posts";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
    <link rel="stylesheet" href="~/dashboard/plugins/summernote/summernote-bs4.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.5/croppie.min.css" />
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Post managament</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-action="Index">Home</a></li>
                        <li class="breadcrumb-item active">Create post</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- SELECT2 EXAMPLE -->
            <div class="card card-default">
                <div class="card-header">
                    <h3 class="card-title">Create post</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-5 offset-3">
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">New post</h3>
                                </div>
                                @if (@ViewBag.AuthError != null)
                                {
                                    <span class="text-danger mt-3">@ViewBag.AuthError</span>
                                }

                                <form method="post" asp-controller="Post" asp-action="Create" enctype="multipart/form-data">
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label>Title</label>
                                            <input type="text" asp-for="@Model.Title" class="form-control" placeholder="Title" />
                                        </div>
                                        <div class="form-group">
                                            <label>Description</label>
                                            <textarea id="summernote" type="text" asp-for="@Model.Description" class="form-control">Place <em>your</em> <u>post</u> <string>heare...</string></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label>Text</label>
                                            <textarea id="text" type="text" asp-for="@Model.FullText" class="form-control">Place <em>your</em> <u>post</u> <string>heare...</string></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label>Category</label>
                                            <select asp-for="CategoryId" asp-items="ViewBag.CategoryList" class="custom-select form-control-border"></select>
                                        </div>
                                        <div class="form-group">
                                            <label>Image</label>
                                            <div class=" input-group">
                                                <div class="custom-file">
                                                    <div class="custom-file">
                                                        <input type="file" id="Image" name="files" asp-for="@Model.File" class="custom-file-input" />
                                                        <label class="custom-file-label">Choose file...</label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label>Cropped Image</label>
                                            <div id="croppedImage"></div>
                                        </div>
                                        <div class="form-group">
                                            <button type="button" id="cropButton" class="btn btn-primary">Crop Image</button>
                                        </div>
                                        <div class="card-footer">
                                            <button type="submit" class="btn btn-primary">Create</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

@section Scripts{
    <script src="~/dashboard/plugins/summernote/summernote-bs5.min.js"></script>
    <script>
        $(function () {
            $('#summernote').summernote({
                minHeight: 200
            })

            $('#text').summernote({
                minHeight: 200
            })
        })
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.5/croppie.min.js"></script>
    <script>
        $(function () {
            var $imageInput = $('#Image');
            var $croppedImage = $('#croppedImage');
            var $cropper;

            // Зберігаємо обрізане зображення на клієнті
            var croppedImageData = null;

            // Ініціалізуємо Croppie при виборі файлу
            $imageInput.on('change', function () {
                var files = this.files;
                var file;

                if (files && files.length) {
                    file = files[0];

                    if (/^image\/\w+$/.test(file.type)) {
                        if ($cropper) {
                            $cropper.destroy();
                        }

                        $croppedImage.empty();

                        $cropper = new Croppie($croppedImage[0], {
                            viewport: { width: 200, height: 200 },
                            boundary: { width: 300, height: 300 },
                            aspectRatio: 1,
                            viewMode: 2,
                            responsive: true,
                            crop: function (event) {
                                // Під час обрізки зберігаємо обрізане зображення на клієнті
                                $cropper.result('base64').then(function (base64) {
                                    croppedImageData = base64;
                                });
                            }
                        });

                        var reader = new FileReader();

                        reader.onload = function (e) {
                            $cropper.bind({
                                url: e.target.result
                            });
                        };

                        reader.readAsDataURL(file);
                    } else {
                        alert('Будь ласка, виберіть зображення.');
                    }
                }
            });

            $('#cropButton').on('click', function () {
                if ($cropper) {
                    // Очікуємо завершення операції і виводимо дані тільки після цього
                    $cropper.result('base64').then(function (base64) {
                        croppedImageData = base64;

                        // Створюємо новий об'єкт DataTransfer
                        let dataTransfer = new DataTransfer();

                        // Створюємо новий Blob з даними з Croppie (виправте тип та розширення, якщо потрібно)
                        let blob = dataURItoBlob(croppedImageData);

                        console.log(blob);

                        // Створюємо новий файл і додаємо його до DataTransfer
                        let file = new File([blob], "filename.png", { type: 'image/png' }); // Встановіть правильний тип і розширення файлу
                        dataTransfer.items.add(file);

                        // Оновлюємо FileList в інпуті
                        var inputElement = document.getElementById('Image'); // Замініть 'Image' на id вашого інпуту
                        inputElement.files = dataTransfer.files;
                    });
                }
            });
            function dataURItoBlob(dataURI) {
                var byteString = atob(dataURI.split(',')[1]);
                var mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];
                var ab = new ArrayBuffer(byteString.length);
                var ia = new Uint8Array(ab);
                for (var i = 0; i < byteString.length; i++) {
                    ia[i] = byteString.charCodeAt(i);
                }
                return new Blob([ab], { type: mimeString });
            }
        });
    </script>
}

TopNews.Web/Views/Post/Update.cshtml
@using TopNews.Core.DTOs.Post;
@model PostDto

@{
    ViewData["Title"] = "Update post";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
    <!-- summernote -->
    <link rel="stylesheet" href="~/dashboard/plugins/summernote/summernote-bs4.min.css">
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Update post</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-controller="Dashboard" asp-action="Index">Home</a></li>
                        <li class="breadcrumb-item active">Update Post</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-7 offset-2">
                    <!-- general form elements -->
                    <div class="card card-warning">
                        <div class="card-header">
                            <h3 class="card-title">Update post</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        @if (@ViewBag.CreatePostError != null)
                        {
                            <span class="text-danger mt-3">@ViewBag.CreatePostError</span>
                        }
                        <form method="post" asp-controller="Post" asp-action="Update" enctype="multipart/form-data">
                            <input type="hidden" asp-for="@Model.PublishDate">
                            <div class="card-body">
                                <div class="form-group">
                                    <label>Title</label>
                                    <input type="text" asp-for="@Model.Title" class="form-control" placeholder="Title">
                                </div>
                                <div class="form-group">
                                    <label>Description</label>
                                    <div class="card-body">
                                        <textarea asp-for="@Model.Description" id="summernote">Place <em>some</em> <u>post description</u> <strong>here</strong>
                                        </textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Text</label>
                                    <div class="card-body">
                                        <textarea asp-for="@Model.FullText" id="text">Place <em>some</em> <u>text</u> <strong>here</strong>
                                        </textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="Category">Category</label>
                                    <select asp-for="CategoryId" class="custom-select form-control-border" asp-items="ViewBag.CategoryList"></select>
                                </div>
                                <div class="form-group">
                                    <label>Image</label>
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <input type="file" id="Image" name="files" class="custom-file-input">
                                            <label class="custom-file-label">Choose file</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    @if (@Model.ImagePath == "Default.png")
                                    {
                                        <img src="~/images/main/content-images/1.jpg" alt="Photo">
                                    }
                                    else
                                    {
                                        <img src="~/images/posts/@Model.ImagePath" alt="Photo">
                                    }
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-warning">Update</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </div>
                <!--/.col (left) -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

@section Scripts{
    <!-- Summernote -->
    <script src="~/dashboard/plugins/summernote/summernote-bs4.min.js"></script>
    <script>
        $(function () {
            // Summernote
            $('#summernote').summernote({
                minHeight: 200
            })
        })
        $(function () {
            // Summernote
            $('#text').summernote({
                minHeight: 400
            })
        })
        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
}