TopNews.Web/Controllers/CategoryController.cs
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using TopNews.Core.DTOs.Category;
using TopNews.Core.DTOs.Post;
using TopNews.Core.DTOs.User;
using TopNews.Core.Interfaces;
using TopNews.Core.Services;
using TopNews.Core.Validation.Category;
using TopNews.Core.Validation.User;
using X.PagedList;

namespace TopNews.Web.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {

        private readonly UserService _userService;
        private readonly ICategoryService _categoryService;
        private readonly IPostService _postService;

        public CategoryController(UserService userService, ICategoryService categoryService, IPostService postService)
        {
            _userService = userService;
            _categoryService = categoryService;
            _postService = postService;
        }

        public IActionResult Index()
        {
            return RedirectToAction(nameof(GetAll));
        }

        #region Get All page
        public async Task<IActionResult> GetAll()
        {
            List<CategoryDto> categories =  await _categoryService.GetAll();
            return View(categories);
        }
        #endregion

        #region Create page
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryDto model)
        {
            CreateCategoryValidation validator = new CreateCategoryValidation();
            var validationResult = await validator.ValidateAsync(model);
            if (validationResult.IsValid)
            {
                var result = await _categoryService.GetByName(model);
                if (!result.Success)
                {
                    ViewBag.AuthError = "Category exists.";
                    return View(model);
                }
                await _categoryService.Create(model);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.AuthError = validationResult.Errors.FirstOrDefault();
            return View(model);
        }
        #endregion

        #region Update page
        public async Task<IActionResult> Update(int id)
        {
            CategoryDto? categoryDto = await _categoryService.Get(id);
            if (categoryDto == null)
            {
                ViewBag.AuthError = "Category not found.";
                return View();
            }
            return View(categoryDto);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(CategoryDto model)
        {
            ServiceResponse result = await _categoryService.GetByName(model);
            if (!result.Success)
            {
                ViewBag.AuthError = "Category exists.";
                return View(model);
            }
            CreateCategoryValidation validator = new CreateCategoryValidation();
            var validationResult = await validator.ValidateAsync(model);
            if (validationResult.IsValid)
            {
                await _categoryService.Update(model);
                return RedirectToAction(nameof(GetAll));
            }
            ViewBag.AuthError = validationResult.Errors.FirstOrDefault();
            return View(model);
        }
        #endregion

        #region Delete
        public async Task<IActionResult> Delete(int id)
        {
            CategoryDto? categoryDto = await _categoryService.Get(id);

            if (categoryDto == null)
            {
                ViewBag.AuthError = "Category not found.";
                return RedirectToAction(nameof(GetAll));
            }

            List<PostDto> posts = await _postService.GetByCategory(id);
            ViewBag.CategoryName = categoryDto.Name;
            ViewBag.IdCategory = categoryDto.Id;

            int pageSize = 20;
            int pageNumber = 1;
            return View("Delete", posts.ToPagedList(pageNumber, pageSize));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteById(int Id)
        {
            await _categoryService.Delete(Id);
            return RedirectToAction(nameof(GetAll));
        }
        #endregion

    }
}

TopNews.Web/Controllers/PostController.cs
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TopNews.Core.DTOs.Category;
using TopNews.Core.DTOs.Post;
using TopNews.Core.Entities.Site;
using TopNews.Core.Interfaces;
using TopNews.Core.Services;
using TopNews.Core.Validation.Category;
using TopNews.Core.Validation.Post;
using X.PagedList;

namespace TopNews.Web.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostService _postService;
        private readonly ICategoryService _categoryService;
        public PostController(IPostService postService, ICategoryService categoryService)
        {
            _postService = postService;
            _categoryService = categoryService;
        }
        public IActionResult Index()
        {
            return RedirectToAction(nameof(GetAll));
        }
        #region Get All page
        [AllowAnonymous]
        public async Task<IActionResult> GetAll(int? page)
        {
            List<PostDto> posts = (await _postService.GetAll()).OrderByDescending(p => p.Id).ToList();
            int pageSize = 20;
            int pageNumber = (page ?? 1);
            return View("GetAll", posts.ToPagedList(pageNumber, pageSize));
        }
        #endregion

        #region Create page
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create()
        {
            await LoadCategories();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create(PostDto model)
        {
            CreatePostValidation validator = new CreatePostValidation();
            ValidationResult validationResult = await validator.ValidateAsync(model);
            if (!validationResult.IsValid)
            {
                ViewBag.AuthError = validationResult.Errors.FirstOrDefault();
                return View();
            }
            IFormFileCollection files = HttpContext.Request.Form.Files;
            model.File = files;
            await _postService.Create(model);
            return RedirectToAction(nameof(GetAll));
        }
        #endregion

        #region Update page
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Update(int id)
        {
            var posts = await _postService.Get(id);
            if (posts == null) return NotFound();
            await LoadCategories();
            return View(posts);
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(PostDto model)
        {
            var validationResult = await new CreatePostValidation().ValidateAsync(model);
            if (validationResult.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                model.File = files;
                await _postService.Update(model);
                return RedirectToAction(nameof(GetAll));
            }
            ViewBag.CreatePostError = validationResult.Errors.FirstOrDefault();
            return View(model);
        }
        #endregion

        #region Delete
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int id)
        {
            PostDto? postDto = await _postService.Get(id);
            if (postDto == null)
            {
                ViewBag.AuthError = "Post not found.";
                return View();
            }
            return View(postDto);
        }
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteById(int id)
        {
            await _postService.Delete(id);
            return RedirectToAction(nameof(GetAll));
        }
        #endregion

        private async Task LoadCategories()
        {
            List<CategoryDto> result = await _categoryService.GetAll();
            @ViewBag.CategoryList = new SelectList((System.Collections.IEnumerable)result,
                nameof(CategoryDto.Id), nameof(CategoryDto.Name)
              );
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> PostsByCategory(int id)
        {
            List<PostDto> posts = await _postService.GetByCategory(id);
            int pageSize = 20;
            int pageNumber = 1;
            return View("GetAll", posts.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Search([FromForm] string searchString)
        {
            List<PostDto> posts = await _postService.Search(searchString);
            int pageSize = 20;
            int pageNumber = 1;
            return View("GetAll", posts.ToPagedList(pageNumber, pageSize));
        }
    }
}

TopNews.Web/Views/Category/Create.cshtml
@using TopNews.Core.DTOs.Category;
@model CategoryDto

@{
    ViewData["Title"] = "Categories";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Category managament</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-action="Index">Home</a></li>
                        <li class="breadcrumb-item active">Create category</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- SELECT2 EXAMPLE -->
            <div class="card card-default">
                <div class="card-header">
                    <h3 class="card-title">Create category</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-5 offset-3">
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">New category</h3>
                                </div>
                                <!-- /.card-header -->
                                <!-- form start -->
                                @if (@ViewBag.AuthError != null)
                                {
                                    <span class="text-danger mt-3">@ViewBag.AuthError</span>
                                }
                                <form method="post" asp-controller="Category" asp-action="Create">
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label>Category</label>
                                            <input type="text" name="name" class="form-control" placeholder="Category name">
                                        </div>
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary">Create</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

TopNews.Web/Views/Category/Delete.cshtml
@using TopNews.Core.DTOs.Post;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;
@using X.PagedList;
@model IPagedList<PostDto>

@{
    ViewData["Title"] = "Categories";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Delete category</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Delete category</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- START ALERTS AND CALLOUTS -->
            <div class="row">

                @if (Model.Count() > 0)
                {
                    <div class="col-md-10 offset-md-1">
                        <h2 class="mb-5">You can't delete category @ViewBag.CategoryName because it contains posts.</h2>
                        <div class="list-group">
                            @foreach (var item in Model)
                            {
                                <div class="list-group-item mb-2">
                                    <div class="row">
                                        <div class="col-8 px-4">
                                            <div class="mb-2">
                                                <h3>@item.Title</h3>
                                            </div>
                                        </div>
                                        <div class="col-4">
                                            <div class="float-right">
                                                <a asp-controller="Post" asp-action="Update" asp-route-id="@item.Id" asp-route-slug="@item.Slug" class="btn btn-block btn-warning d-inline">Edit</a>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            }
                            <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                                @Html.PagedListPager(Model, page => Url.Action("index", new { page = page }), new PagedListRenderOptions()
                            {
                            ActiveLiElementClass = "active",
                            PageClasses = new[]{ "page-link"},
                            LiElementClasses=new[] { "page-item" },
                            UlElementClasses = new[] { "pagination","justify-content-center", "mt-3" },
                            LinkToNextPageFormat = "Next",
                            LinkToPreviousPageFormat = "Prev",
                            MaximumPageNumbersToDisplay = 3,
                            DisplayLinkToPreviousPage = PagedListDisplayMode.Never,
                            DisplayLinkToNextPage = PagedListDisplayMode.Never
                            })
                            </div>
                        </div>
                    </div>
                }
                else
                {
                    <div class="col-md-6 offset-3">
                        <div class="card card-default">
                            <div class="card-header">
                                <h3 class="card-title">
                                    <i class="fas fa-exclamation-triangle"></i>
                                    Warning!
                                </h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="callout callout-danger">
                                    @if (@ViewBag.AuthError != null)
                                    {
                                        <span class="text-danger">@ViewBag.AuthError</span>
                                    }
                                    <h5 class="mb-4">Do you really wants to delete category @ViewBag.CategoryName?</h5>
                                    <form method="post" asp-controller="Category" asp-action="DeleteById" asp-route-id="@ViewBag.IdCategory">
                                        <div class="card-footer">
                                            <button type="submit" style="width: 25%;" class="btn btn-block btn-danger btn-sm">Delete</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                }

            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

TopNews.Web/Views/Category/GetAll.cshtml
@using Microsoft.AspNetCore.Identity;
@using TopNews.Core.DTOs.Category;
@using TopNews.Core.DTOs.User;
@using TopNews.Core.Entities.User;
@model List<CategoryDto>
@inject UserManager<AppUser> UserManager

@{
    var user = await UserManager.GetUserAsync(User);
}
@{
    <!-- DataTables -->
    <link rel="stylesheet" href="~/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/assets/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
}
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>All categories</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">categories</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Categories list with minimal information</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Name</th>
                                        @if (@User.IsInRole("Administrator"))
                                        {
                                            <th>Edit</th>
                                            <th>Delete</th>
                                        }

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Id</td>
                                            <td>@item.Name</td>
                                            @if (@User.IsInRole("Administrator"))
                                            {
                                                <td><a asp-controller="Category" asp-action="Update" asp-route-id="@item.Id" class="btn btn-block btn-warning btn-sm">Edit</a></td>
                                                <td><a asp-controller="Category" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-block btn-danger btn-sm">Delete</a></td>
                                            }
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.col -->
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
</div>
<!-- /.content -->

TopNews.Web/Views/Category/Index.cshtml
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Dashboard</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a class="text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6">

                    <div class="card">
                        <div class="card-header border-0">
                            <div class="d-flex justify-content-between">
                                <h3 class="card-title">Online Store Visitors</h3>
                                <a href="javascript:void(0);">View Report</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="d-flex">
                                <p class="d-flex flex-column">
                                    <span class="text-bold text-lg">820</span>
                                    <span>Visitors Over Time</span>
                                </p>
                                <p class="ml-auto d-flex flex-column text-right">
                                    <span class="text-success">
                                        <i class="fas fa-arrow-up"></i> 12.5%
                                    </span>
                                    <span class="text-muted">Since last week</span>
                                </p>
                            </div>
                            <!-- /.d-flex -->

                            <div class="position-relative mb-4">
                                <canvas id="visitors-chart" height="200"></canvas>
                            </div>

                            <div class="d-flex flex-row justify-content-end">
                                <span class="mr-2">
                                    <i class="fas fa-square text-primary"></i> This Week
                                </span>

                                <span>
                                    <i class="fas fa-square text-gray"></i> Last Week
                                </span>
                            </div>
                        </div>
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col-md-6 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
</div>

TopNews.Web/Views/Category/Update.cshtml
@using TopNews.Core.DTOs.Category;
@model CategoryDto

@{
    ViewData["Title"] = "Categories";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Category managament</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-action="Index">Home</a></li>
                        <li class="breadcrumb-item active">Edit category</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- SELECT2 EXAMPLE -->
            <div class="card card-default">
                <div class="card-header">
                    <h3 class="card-title">Update category</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-5 offset-3">
                            <div class="card card-warning">
                                <div class="card-header">
                                    <h3 class="card-title">Update category</h3>
                                </div>
                                <!-- /.card-header -->
                                <!-- form start -->
                                @if (@ViewBag.AuthError != null)
                                {
                                    <span class="text-danger mt-3">@ViewBag.AuthError</span>
                                }
                                <form method="post" asp-controller="Category" asp-action="Update">
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label>Category</label>
                                            <input type="text" asp-for="Name" name="name" class="form-control" placeholder="Category name">
                                            <span class="text-danger" asp-validation-for="Name"></span>
                                        </div>
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-warning">Update</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>