TopNews.Web/Controllers/DashdoardAccessesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TopNews.Core.DTOs.Category;
using TopNews.Core.DTOs.Ip;
using TopNews.Core.DTOs.Post;
using TopNews.Core.Interfaces;
using TopNews.Core.Services;
using TopNews.Core.Validation.Category;
using TopNews.Core.Validation.Id;
using TopNews.Core.Validation.Post;
using X.PagedList;

namespace TopNews.Web.Controllers
{
    public class DashdoardAccessesController : Controller
    {
        private readonly IDashdoardAccessService _ipService;
        public DashdoardAccessesController(IDashdoardAccessService dashdoardAccessService)
        {
            _ipService = dashdoardAccessService;
        }
        public IActionResult Index()
        {
            return RedirectToAction(nameof(GetAll));
        }

        #region Get All page
        public async Task<IActionResult> GetAll()
        {
            List<DashdoardAccessDto> ips = await _ipService.GetAll();
            return View(ips);
        }
        #endregion

        #region Create page
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DashdoardAccessDto model)
        {
            var validationResult = await new CreateDashdoardAccessesValidation().ValidateAsync(model);
            if (validationResult.IsValid)
            {
                DashdoardAccessDto? result = await _ipService.Get(model.IpAddress);
                if (result != null)
                {
                    ViewBag.AuthError = "DashdoardAccesses exists.";
                    return View(model);
                }
                await _ipService.Create(model);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.AuthError = validationResult.Errors.FirstOrDefault();
            return View(model);
        }
        #endregion

        #region Update page
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Update(int id)
        {
            var ip = await _ipService.Get(id);
            if (ip == null) return NotFound();
            return View(ip);
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(DashdoardAccessDto model)
        {
            var validationResult = await new CreateDashdoardAccessesValidation().ValidateAsync(model);
            if (validationResult.IsValid)
            {
                await _ipService.Update(model);
                return RedirectToAction(nameof(GetAll));
            }
            ViewBag.AuthError = validationResult.Errors.FirstOrDefault();
            return View(model);
        }
        #endregion

        #region Delete
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int id)
        {
            DashdoardAccessDto? model = await _ipService.Get(id);
            if (model == null)
            {
                ViewBag.AuthError = "IP not found.";
                return RedirectToAction(nameof(GetAll));
            }
            return View(model);
        }
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteById(int Id)
        {
            await _ipService.Delete(Id);
            return RedirectToAction(nameof(GetAll));
        }
        #endregion
    }
}

TopNews.Web/Views/DashdoardAccesses/Create.cshtml
@using TopNews.Core.DTOs.Ip;
@model DashdoardAccessDto

@{
    ViewData["Title"] = "IP";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Category managament</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-action="Index">Home</a></li>
                        <li class="breadcrumb-item active">Create IP</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- SELECT2 EXAMPLE -->
            <div class="card card-default">
                <div class="card-header">
                    <h3 class="card-title">Create IP</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-5 offset-3">
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">New IP</h3>
                                </div>
                                <!-- /.card-header -->
                                <!-- form start -->
                                @if (@ViewBag.AuthError != null)
                                {
                                    <span class="text-danger mt-3">@ViewBag.AuthError</span>
                                }
                                <form method="post" asp-controller="DashdoardAccesses" asp-action="Create">
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label>IP Address</label>
                                            <input type="text" name="IpAddress" class="form-control" placeholder="IP Address">
                                        </div>
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary">Create</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

TopNews.Web/Views/DashdoardAccesses/Delete.cshtml
@using TopNews.Core.DTOs.Ip;
@model DashdoardAccessDto

@{
    ViewData["Title"] = "Delete post";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Delete post</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Delete IP</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- START ALERTS AND CALLOUTS -->
            <div class="row">
                <div class="col-md-6 offset-3">
                    <div class="card card-default">
                        <div class="card-header">
                            <h3 class="card-title">
                                <i class="fas fa-exclamation-triangle"></i>
                                Warning!
                            </h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <div class="callout callout-danger">
                                @if (@ViewBag.AuthError != null)
                                {
                                    <span class="text-danger">@ViewBag.AuthError</span>
                                }
                                <h5 class="mb-4">Do you really wants to delete post @Model.IpAddress</h5>
                                <a asp-action="DeleteById" asp-controller="DashdoardAccesses" asp-route-id="@Model.Id" style="width: 25%;" class="btn btn-block btn-danger btn-sm">Delete</a>
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

TopNews.Web/Views/DashdoardAccesses/GetAll.cshtml
@using Microsoft.AspNetCore.Identity;
@using TopNews.Core.DTOs.Ip;
@using TopNews.Core.Entities.User;
@model List<DashdoardAccessDto>
@inject UserManager<AppUser> UserManager

@{
    var user = await UserManager.GetUserAsync(User);
}
@{
    <!-- DataTables -->
    <link rel="stylesheet" href="~/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/assets/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
}
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>All IP</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">IP</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">IP list with minimal information</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>IpAddress</th>
                                        @if (@User.IsInRole("Administrator"))
                                        {
                                            <th>Edit</th>
                                            <th>Delete</th>
                                        }

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Id</td>
                                            <td>@item.IpAddress</td>
                                            @if (@User.IsInRole("Administrator"))
                                            {
                                                <td><a asp-controller="DashdoardAccesses" asp-action="Update" asp-route-id="@item.Id" class="btn btn-block btn-warning btn-sm">Edit</a></td>
                                                <td><a asp-controller="DashdoardAccesses" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-block btn-danger btn-sm">Delete</a></td>
                                            }
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.col -->
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
</div>
<!-- /.content -->

TopNews.Web/Views/DashdoardAccesses/Update.cshtml
@using TopNews.Core.DTOs.Ip;
@model DashdoardAccessDto

@{
    ViewData["Title"] = "Categories";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>IP managament</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-action="Index">Home</a></li>
                        <li class="breadcrumb-item active">Edit IP</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- SELECT2 EXAMPLE -->
            <div class="card card-default">
                <div class="card-header">
                    <h3 class="card-title">Update IP</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-5 offset-3">
                            <div class="card card-warning">
                                <div class="card-header">
                                    <h3 class="card-title">Update IP</h3>
                                </div>
                                <!-- /.card-header -->
                                <!-- form start -->
                                @if (@ViewBag.AuthError != null)
                                {
                                    <span class="text-danger mt-3">@ViewBag.AuthError</span>
                                }
                                <form method="post" asp-controller="DashdoardAccesses" asp-action="Update">
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label>IP Adrress</label>
                                            <input type="text" asp-for="IpAddress" name="IpAddress" class="form-control" placeholder="IP Adrress">
                                        </div>
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-warning">Update</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>